pages:
  - codename: "alvin"
    name: "Alvin Week Menu"
    homepage: "https://www.alvinrestaurace.cz/"
    url: "https://www.alvinrestaurace.cz/obchod/"
    query: ".wnd-no-cols"
    filters:
      cut:
        after: "*Informace o alergenech získáte u obsluhy, nebo v rozvozovém menu.*"
        before: "*TÝDENNÍ MENU*"
      day:
        enabled: true
    tags: ["rh", "cz", "medlanky", "ita"]

  - codename: "moravia"
    name: "Moravia Week Menu"
    homepage: "https://www.pivovarskarestauracemoravia.cz/"
    url: "https://www.pivovarskarestauracemoravia.cz/"
    query: "#block-dennimenu .active"
    tags: ["rh", "cz", "medlanky"]

  - codename: "himalaya"
    name: "Himalaya"
    homepage: "https://www.himalayarestaurace.cz/"
    url: "https://www.himalayarestaurace.cz/denni-menu/"
    resolver: "img"
    query: "div#menu img"
    cache_policy: "no-cache"
    tags: ["ns", "vlnena", "india", "city"]

  - codename: "charlies_square"
    name: "Charlie's square"
    homepage: "https://www.charliessquare.cz/"
    url: "https://www.charliessquare.cz/menu"
    xpath: "//div[@class='entry-content']//table[not(contains(@class, 'menu-bar'))]"
    tags: ["ns", "vlnena", "city", "cz"]
    filters:
      day:
        enabled: false
      html:
        tables: custom

  - codename: "charlies_mill"
    name: "Charlie's mill"
    homepage: "https://www.charliesmill.cz/"
    url: "https://www.charliesmill.cz/menu"
    xpath: "//div[@class='entry-content']//table[not(contains(@class, 'menu-bar'))]"
    tags: ["cz"]
    filters:
      day:
        enabled: true
      html:
        tables: custom

  - codename: "jean_pauls"
    name: "Jean Pauls Behounska"
    homepage: "http://jpbistro.cz/"
    url: "https://jpbistro.cz/assets/menu/obed-menu/obed-behounska.pdf"
    resolver: "pdf"
    tags: ["ns", "vlnena", "gd", "ita", "city"]

  - codename: "jean_pauls_techpark"
    name: "Jean Pauls Technologicky park"
    homepage: "http://jpbistro.cz/"
    url: "https://jpbistro.cz/assets/menu/obed-menu/obed-technopark.pdf"
    resolver: "pdf"
    tags: ["ita", "tp", "medlanky", "rh"]

  - codename: "drevak"
    name: "U Drevaka"
    tags: ["fi", "cz"]
    homepage: "https://udrevaka.cz/"
    url: "https://udrevaka.cz/pages/poledni-menu"
    # TODO: https://udrevaka.cz/api/public/custom-page/poledni-menu
    resolver: url_only
    xpath: '//div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div'

  - codename: "padagali"
    name: "Padagali"
    homepage: "https://padagali.cz/"
    url: "https://padagali.choiceqr.com/"
    tags: ["fi", "india", "asia"]
    query: "#mobile-section-menu"
    resolver: "iframe"

  - codename: "nepal"
    name: "Nepal"
    url: "https://nepalbrno.cz/weekly-menu/"
    homepage: "https://nepalbrno.cz/"
    query: "#Content .the_content_wrapper"
    tags: ["rh", "india", asia]
    filters:
      day:
        enabled: true
      cut:
        after: "Seznam alergenů"
      html:
        tables: custom

  - codename: "globus"
    name: "Globus Brno"
    url: "https://www.globus.cz/brno/sluzby-a-produkty/restaurace"
    homepage: "https://www.globus.cz/brno/"
    tags: ["rh", "fast"]
    xpath: "/html/body/div[2]/div/div[2]/div[1]/div/div/div"
    filters:
      day:
        enabled: true
      html:
        tables: custom

  - codename: "annapurna"
    name: "Annapurna"
    homepage: "http://www.indicka-restaurace-annapurna.cz/"
    url: "http://www.indicka-restaurace-annapurna.cz/"
    query: "div.TJStrana"
    tags: ["city", "ns", "vlnena", "india", "asia"]
    filters:
      day:
        enabled: true
      cut:
        after: "Polední menu podáváme"

  - codename: "krava"
    name: "Monte Bu"
    homepage: "https://www.monte-bu.cz/"
    url: "https://www.monte-bu.cz/menu.php#poledni-section"
    query: ".menu-details .today"
    tags: ["rh", "ns", "vlnena", "cz", "steak"]
    filters:
      day:
        enabled: true

  - codename: "sabaidy"
    name: "Sabaidy"
    url: "http://www.amphone.eu/restaurace"
    homepage: "http://www.amphone.eu/restaurace"
    query: "li:first-child"
    tags: ["city", "asia", gd]
    filters:
      day:
        enabled: true

  - codename: seminar
    name: U seminaru
    url: "http://www.useminaru.cz/menu.php"
    homepage: "http://www.useminaru.cz/"
    query: ".maintab .bold"
    tags: ["city", "cz", "fi", "gd"]
    filters:
      day:
        enabled: true
      html:
        tables: custom

  - codename: tripoli
    name: Tripoli Vankovka
    url: http://www.tripolivankovka.cz/denni-menu
    homepage: http://www.tripolivankovka.cz/
    query: "div.menu-for-one-day"
    tags: ["city", "ita", "pizza", "vankovka", "ns", "vlnena"]
    filters:
      day:
        enabled: true
      cut:
        after: "Nabídka baru"

  - codename: husa-vankovka
    name: Potrefena husa Vankovka
    url: https://www.potrefenahusabrno.cz/menu/
    homepage: https://www.potrefenahusabrno.cz/
    query: "div.menu-for-one-day"
    tags: ["city", "cz", "vankovka", "ns", "vlnena"]
    filters:
      day:
        enabled: true
      cut:
        after: "Nabídka baru"

  - codename: padowetz
    name: Padowetz
    url: http://www.restaurant-padowetz.cz/poledni-menu
    homepage: http://www.restaurant-padowetz.cz/
    query: ".content"
    tags: ["city", "cz", "ns", "vlnena"]
    filters:
      cut:
        after: "[stáhnout menu v PDF]"
      cutLine:
        minLen: 10

  - codename: diva_bara
    name: Diva bara
    url: http://www.restauracedivabara.cz/menu/
    homepage: http://www.restauracedivabara.cz/
    query: "div.daily-menu"
    tags: ["fi", "cz"]
    filters:
      day:
        enabled: true

  - codename: na_purkynce
    name: "Na Purkyňce"
    url: https://www.menicka.cz/2647-na-purkynce.html
    homepage: https://www.menicka.cz/2647-na-purkynce.html
    query: ".menicka"
    tags: ["rh", "cz"]
    filters:
      day:
        enabled: true

  - codename: spravne_misto
    name: "Spravne misto"
    url: https://spravnemisto.cz/cs-cz
    homepage: https://spravnemisto.cz/
    query: "#menu_dialog table"
    tags: ["rh", "cz"]
    filters:
      day:
        enabled: true
      cut:
        after: "Týdenní menu"

  - codename: ubaumanu
    name: U Baumanu
    url: https://ubaumannu.cz/menu
    homepage: https://ubaumannu.cz/
    tags: ["ceska", "cz"]
    query: ".Main-content"
    filters:
      day:
        enabled: true
      cut:
        before: "Cena za menu včetně polévky je 149 Kč."
        after: "Menu podáváme od 11 hod. do 14 hod. případně do vyprodání."

  - codename: garden_food_concept
    name: Garden Food Concept
    homepage: https://www.gardenfoodconcept.cz/
    tags: ["city", "gd"]
    url: https://www.gardenfoodconcept.cz/poledni-menu/
    resolver: img
    query: ".b-img picture img"

  - codename: stopkova
    name: Stopkova Plzenska Pivnice
    homepage: https://www.kolkovna.cz/cs/stopkova-plzenska-pivnice-16
    tags: ["cz", "gd", "ns", "vlnena", "city"]
    url: https://stopkova.kolkovna.cz/#poledni-menu
    query: "div.op-menu.active"
    filters:
      day:
        enabled: true
      html:
        tables: custom

  - codename: sagram
    name: Sagram
    homepage: https://sargamrestaurace.cz/
    tags: ["ns", "vlnena", "india", "asia"]
    url: https://sargamrestaurace.cz/DMenuItems
    query: "main div.row:nth-child(n+5)"
    filters:
      day:
        enabled: true
      cut:
        after: "#Sunday"

  - codename: masny_ruzek
    name: Masny ruzek
    tags: ["city", "cz", "ns", "vlnena"]
    homepage: https://www.masnyruzek.cz/
    url: https://www.menicka.cz/api/iframe/?id=6956
    query: "body"
    filters:
      day:
        enabled: true

  - codename: fansipan
    name: FANSIPAN
    tags: ["medlanky", "asia", "vietnam", "fb"]
    homepage: https://www.facebook.com/profile.php?id=61552598167979
    url: https://www.facebook.com/profile.php?id=61552598167979
    resolver: url_only

  - codename: happy-tea-house
    name: Happy Tea House (Vesela Cajovna)
    tags: ["city", "india"]
    homepage: https://www.veselacajovna.cz/
    url: https://www.veselacajovna.cz/tydenni-nabidka/
    resolver: iframe

  - codename: nova-chaloupka
    name: Nova Chaloupka
    tags: ["medlanky", "cz"]
    homepage: https://restauracechaloupka.cz/
    url: https://restauracechaloupka.cz/index.php?show=poledni-menu
    query: "body div.container"
    filters:
      day:
        enabled: true

  - codename: grand-kitchen-vlnena
    name: Grand Kitchen Vlnena
    tags: ["ns", "vlnena", "city"]
    homepage: https://www.grandkitchenvlnena.cz/
    url: https://www.grandkitchenvlnena.cz/menu/
    query: "section.fly-dish-menu.jidel"
    resolver: iframe
    filters:
      day:
        enabled: true
