services:
  otel:
    image: grafana/otel-lgtm
    ports:
      - "127.0.0.1:5050:3000"
      - "4317:4317"
      - "127.0.0.1:4318:4318"
    environment:
      ENABLE_LOGS_OTELCOL: true
      ENABLE_LOGS_TEMPO: true
    healthcheck:
      test: test -e /tmp/ready
      interval: 5s
      timeout: 2s
      retries: 20

    volumes:
      - otel-data:/data

volumes:
  otel-data: {}
