services:
  otel:
    image: grafana/otel-lgtm
    ports:
      - "127.0.0.1:5050:3000"
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:4318:4318"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: false
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_ANONYMOUS_ORG_NAME: pstanko.net
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GF_AUTH_PASSWORD}
      GF_AUTH_BASIC_ENABLED: true
      GF_AUTH_BASIC_USER: admin
      GF_AUTH_BASIC_PASSWORD: ${GF_AUTH_PASSWORD}
      ENABLE_LOGS_OTELCOL: true
      ENABLE_LOGS_TEMPO: true
    healthcheck:
      test: test -e /tmp/ready
      interval: 5s
      timeout: 2s
      retries: 20

    volumes:
      - otel-data:/data

volumes:
  otel-data: {}
