include:
  - compose.otel.yaml

services:
  miniscrape:
    image: miniscrape
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      LOG_LEVEL: info
      OTEL_ENABLED: true
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_INSECURE: true
      ENV_NAME: dev
      SERVICE_NAME: miniscrape
      SERVICE_VERSION: v1.0.0
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - miniscrape-run:/app/runtime
  
  miniscrape-ui:
    image: miniscrape-ui
    build: ./miniscrape-ui
    ports:
      - "127.0.0.1:3000:3000"
    restart: on-failure
    environment:
      LOG_LEVEL: info
      SERVICE_MINISCRAPE_URL: "http://miniscrape:8080"
    healthcheck:
      test: ["CMD", 'node', '-e', 'fetch("http://localhost:3000/healthz").then(r => process.exit(r.ok ? 0 : 1))']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  miniscrape-run: