services:
  otel:
    image: grafana/otel-lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: false
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_ANONYMOUS_ORG_NAME: pstanko.net
      GF_AUTH_BASIC_ENABLED: true
      GF_AUTH_BASIC_USER: admin
      GF_AUTH_BASIC_PASS: Ult1mat3Pa$$word&42
