services:
  miniscrape:
    image: miniscrape
    build: .
    ports:
      - "8080:8080"
    environment:
      LOG_LEVEL: info
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
