categories:
  - food
  - cinema

cache:
  enabled: true
  update: false
  root: ./runtime/cache

web:
  addr: ':8080'
  domain: localhost

log:
  dir: ./runtime/log
  level: info

otel:
  enabled: true
  endpoint: 'localhost:4317'
  protocol: 'grpc'
  insecure: true
