pages:
  - codename: "alvin"
    name: "Alvin Week Menu"
    homepage: "https://www.alvinrestaurace.cz/"
    url: "https://www.alvinrestaurace.cz/obchod/"
    query: ".content"
    filters:
      cut:
        after: "*Informace o alergenech získáte u obsluhy, nebo v rozvozovém menu.*"
        before: "*TÝDENNÍ MENU*"
      day:
        enabled: true
    tags: [ "rh", "cz", "medlanky" ]
