pages:
  - codename: "alvin"
    name: "Alvin Week Menu"
    homepage: "https://www.alvinrestaurace.cz/"
    url: "https://www.alvinrestaurace.cz/obchod/"
    query: ".content"
    filters:
      cut:
        after: "*Informace o alergenech získáte u obsluhy, nebo v rozvozovém menu.*"
        before: "*TÝDENNÍ MENU*"
      day:
        enabled: true
    tags: [ "rh", "food", "cz", "medlanky", "ita" ]

  - codename: "moravia"
    name: "Moravia Week Menu"
    homepage: "https://www.pivovarskarestauracemoravia.cz/"
    url: "https://www.pivovarskarestauracemoravia.cz/"
    query: "#block-dennimenu .active"
    tags: [ "rh", "food", "cz", "medlanky" ]

  - codename: "himalaya"
    name: "Himalaya"
    homepage: "https://www.himalayarestaurace.cz/"
    url: "https://www.himalayarestaurace.cz/denni-menu/"
    resolver: "url-only"
    cache_policy: "no-cache"
    tags: [ "ns", "food", "india", "city" ]

  - codename: "charlies_square"
    name: "Charlie's square"
    homepage: "https://www.charliessquare.cz/"
    url: "https://www.charliessquare.cz/"
    xpath: "//div[@class='entry-content']//table[not(contains(@class, 'menu-bar'))]"
    tags: [ "ns", "city", "cz" ]
    filters:
      html:
        pretty_tables: True
      cut:
        after: "NABÍDKA BARU"
