name: Unit tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: setup golang v1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Unit test
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
          task test

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "reports/*.xml"
        if: always()
