name: Unit tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup golang v1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Unit test
        run: make test